name: PullRequest-QA-Workflow

on:
  pull_request:
    branches:
      - '*'

env:
  BRANCH_NAME: ${{ github.head_ref }}

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker/compose:1.29.2
        options: --privileged
        env:
          DOCKER_COMPOSE_VERSION: 1.29.2

    steps:
      - name: 'Basic info'
        run: |
          echo "Executing pull request workflow for branch $BRANCH_NAME, on: ${{ github.repository }}"

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and run Docker containers
        run: |
          docker-compose up --build -d

      - name: Wait for API to be ready
        run: |
          docker-compose run --rm api sh -c 'while ! nc -z localhost 3000; do sleep 1; done'

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: docker-compose exec api npm install

      - name: Create dist folder
        run: docker-compose exec api npm run build

      - name: Run Unit Test
        run: docker-compose exec api npm run test

      - name: Stop Docker containers
        run: docker-compose down
