## This workflow is not required on this project but I want to show how actually I work when I am working

name: PullRequest-QA-Workflow

on: [pull_request]

env:
  BRANCH_NAME: ${{ github.head_ref }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Basic info'
        run: |
          echo "Executing pull request workflow for branch $BRANCH_NAME, on: ${{ github.repository }}"
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run:  npm  install

      - name: create dist folder
        run: npm  build

      - name: Run Unit Test
        run: npm run test