## This workflow is not required on this project but I want to show how actually I work when I am working

name: Test-Deploy-Main-Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run:  npm install

      - name: create dist folder
        run: npm build

      - name: Run Integration Test
        run: npm run test:e2e
