name: Test-Deploy-Main-Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: alpine:latest
      options: --user root
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build and run Docker containers
        run: |
          docker-compose up --build -d
          

      - name: Run Integration Test
        run: |
          docker-compose run api npm run test:e2e

      - name: Stop Docker containers
        run: |
          docker-compose down

