name: Test-Deploy-Main-Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Build Docker image
        run: docker build -t myapp .

      - name: Install dependencies with Docker
        run: docker run -v $PWD:/app -w /app myapp npm install

      - name: create dist folder
        run: docker run -v $PWD:/app -w /app myapp npm build

      - name: Run Integration Test with Docker
        run: docker run -v $PWD:/app -w /app myapp npm run test:e2e
