name: Test-Deploy-Main-Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and run Docker containers
        run: |
          docker-compose up --build -d

      - name: Install dependencies with Docker Compose
        run: docker-compose exec api sh -c "npm install"

      - name: Create dist folder
        run: |
          docker-compose run api npm run build

      - name: Run Integration Test
        run: |
          docker-compose run api npm run test:e2e

      - name: Stop Docker containers
        run: |
          docker-compose down

